export const ADD_ING="ADD_INGREDIENT";
export const REM_ING="REMOVE_INGREDIENT";
export const SET_ING="SET_INGREDIENT";
export const FETCH_ING_FAILED="FETCH_INGREDIENTS_FAILED";

export const PURCHASE_BURGER_SUCCESS="PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL="PURCHASE_BURGER_FAIL";
export const PURCHASE_BURGER_START="PURCHASE_BURGER_START";
export const PURCHASE_INIT="PURCHASE_INIT";

export const FETCH_ORDERS_START="FETCH_ORDER_START";
export const FETCH_ORDERS_SUCCESS="FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL="FETCH_ORDERS_FAIL";